### ISSUE TITLE
TypeError: d.split is not a function after update to 1.12.0

### ISSUE THREAD

**Issue by Routout** [MindFreeze/ha-sankey-chart#110]
Updated also HA and HAOS to the latest versions.

Config:
```
type: vertical-stack
cards:
  - type: energy-date-selection
  - type: custom:sankey-chart
    min_state: 0
    show_names: true
    height: 300
    unit_prefix: k
    round: 1
    min_box_height: 3
    min_box_distance: 5
    show_states: true
    show_units: true
    energy_date_selection: true
    sections:
      - entities:
          - entity_id: sensor.verkko_kokonaiskulutus_kwh
            type: entity
            name: Kokonaiskulutus
            children:
              - lämmitys
              - kodinkoneet
              - valo
              - unknown
      - entities:
          - entity_id: lämmitys
            type: remaining_child_state
            color: rgb(150,100,100)
            name: []
            children:
              - sensor.ilp_rasia_energy
              - sensor.kylppari_lattia_heatit_electric_consumption_kwh
              - sensor.shelly_iv_switch_0_energy
              - sensor.shelly_eteinen_lattia_switch_0_energy
          - entity_id: kodinkoneet
            type: remaining_child_state
            color: rgb(150,100,100)
            name: []
            children:
              - sensor.0xa4c1387d1d1c4841_energy
              - sensor.0xa4c13827a1acdd0b_energy
              - sensor.0xa4c13888930d4846_energy
              - sensor.serveri_energy
          - entity_id: valo
            type: remaining_child_state
            name: []
            color: yellow
            children:
              - sensor.keittio_energy
              - sensor.makkari_energy
              - sensor.wc_valo_energy
          - entity_id: unknown
            type: remaining_parent_state
            name: Tuntematon
            color: rgb(100,100,100)
            children: []
      - entities:
          - entity_id: sensor.kylppari_lattia_heatit_electric_consumption_kwh
            type: entity
            name: Kylppäri lämmitys
            color: rgb(255,100,0)
            children: []
          - entity_id: sensor.shelly_eteinen_lattia_switch_0_energy
            type: entity
            name: Eteinen lämmitys
            color: rgb(255,100,0)
            children: []
          - entity_id: sensor.ilp_rasia_energy
            type: entity
            name: ILP
            color: rgb(255,100,0)
            children: []
          - entity_id: sensor.shelly_iv_switch_0_energy
            type: entity
            name: Ilmanvaihto
            color: rgb(50,111,120)
            children: []
          - entity_id: sensor.0xa4c1387d1d1c4841_energy
            type: entity
            name: Pakastin
            children: []
          - entity_id: sensor.0xa4c13827a1acdd0b_energy
            type: entity
            name: Astianpesukone
            color: rgb(0,255,0)
            children: []
          - entity_id: sensor.serveri_energy
            type: entity
            name: Serveri ja TV
            color: rgb(0,255,0)
            children: []
          - entity_id: sensor.0xa4c13888930d4846_energy
            type: entity
            name: Pesukone
            color: rgb(0,255,0)
            children: []
          - entity_id: sensor.keittio_energy
            type: entity
            name: Keittiö valo
            color: yellow
            children: []
          - entity_id: sensor.makkari_energy
            type: entity
            name: Makkari valo
            color: yellow
            children: []
          - entity_id: sensor.wc_valo_energy
            type: entity
            name: WC valo
            color: yellow
            children: []
```

**Comment by MindFreeze** [comment]
Why do you have empty arrays for name? Names are strings

**Comment by Routout** [comment]
> Why do you have empty arrays for name? Names are strings

Not sure if those have been like that from the start. I haven't done anything to config for months and now it just stopped working.
Anyway, removing all `name: []` seem to fix the problem, thanks for help.
